game.name = Casono
# Default client command (example)
game.command = java -jar casono.jar client <serverip>:<serverport> [username]
# Explicit client command property
game.client.command = java -jar casono.jar client <serverip>:<serverport> [username]
# Server command example
game.server.command = java -jar casono.jar server <listenport>
game.description.file = index.html
game.screenshot.file = screenshot.png
game.use = true
game.year = 2026
game.developers = Lars Winzer, Jona Walpert, Matthis Müller, Julian Gerber
